<a href="https://colab.research.google.com/github/Sam-Batisti/Hackatlon_DataScience_POD/blob/main/Dataprep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Conexão Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

###Install

In [3]:
# !pip install pyspark

###Bibliotecas Iniciais

In [4]:
# from pyspark.sql import SparkSession
# from pyspark.sql import functions as F
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import pod_academy_functions as pod

-----------------------------------------------------
------------ PoD Academy Functions ------------------
Só Alegria!
Você está usando o pacote de funções da PoD Academy
Turma: 2023
Autor: PoD Academy
Professor: Bruno Jardim
Versão: 1.0.0
Data: 08/10/2023
-----------------------------------------------------

Dados

In [5]:
# Arquivos
df_app_test = pd.read_csv ('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/application_test.csv')
df_app_train = pd.read_csv ('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/application_train.csv')
# df_pos_cash = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/POS_CASH_balance.csv'
# df_bureau = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/bureau.csv'
# df_bureau_balance = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/bureau_balance.csv'
# df_cc_balance = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/credit_card_balance.csv'
# df_install_pay = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/installments_payments.csv'
# df_prev_app ='/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/previous_application.csv'
# df_sample = '/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/pod-academy-analise-de-credito-para-fintech/sample_submission.csv'

In [6]:
df_app_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
0,247330,0,Cash loans,F,N,N,0,157500.0,706410.0,67072.5,...,0.824762,0.333516,0.293260,0.564878,0.115058,0.655605,0.415562,0.092643,0.723331,0.796523
1,425716,1,Cash loans,F,Y,Y,1,121500.0,545040.0,25407.0,...,0.416260,0.404293,0.137944,0.457971,0.303691,0.215059,0.838892,0.608335,0.585643,0.298456
2,331625,0,Cash loans,M,Y,Y,1,225000.0,942300.0,27679.5,...,0.037711,0.124465,0.091840,0.364601,0.978220,0.520309,0.594523,0.559650,0.361873,0.254804
3,455397,0,Revolving loans,F,N,Y,2,144000.0,180000.0,9000.0,...,0.784630,0.831403,0.210872,0.049639,0.814219,0.830179,0.755163,0.216664,0.603002,0.429001
4,449114,0,Cash loans,F,N,Y,0,112500.0,729792.0,37390.5,...,0.265381,0.655344,0.668705,0.171391,0.335702,0.585494,0.619551,0.686738,0.540449,0.343632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,239009,0,Cash loans,F,N,Y,0,121500.0,675000.0,32602.5,...,0.214615,0.915096,0.760514,0.720699,0.875196,0.206345,0.359596,0.937269,0.699642,0.231518
215253,399937,0,Cash loans,F,N,N,2,225000.0,509922.0,40419.0,...,0.103347,0.958918,0.271508,0.308291,0.566643,0.942430,0.771174,0.495740,0.451506,0.601316
215254,253016,0,Cash loans,M,Y,Y,0,450000.0,1125000.0,33025.5,...,0.572026,0.709654,0.523142,0.424053,0.269128,0.789032,0.725667,0.160264,0.250138,0.573689
215255,270275,0,Revolving loans,M,Y,Y,1,180000.0,270000.0,13500.0,...,0.421224,0.175427,0.932756,0.585846,0.671286,0.519467,0.849646,0.485528,0.161590,0.091153
215256,241394,1,Cash loans,M,Y,Y,0,157500.0,729792.0,35239.5,...,0.605445,0.741123,0.288505,0.696274,0.463532,0.651455,0.617544,0.817317,0.130288,0.220554

In [7]:
# Garantir validação cruzada Holdout 70/30
train,test = train_test_split(df_app_train, test_size = 0.3, random_state=42)

train.shape, test.shape

((150679, 172), (64578, 172))

In [8]:
train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
45499,102669,0,Cash loans,F,N,Y,0,157500.0,709033.5,39721.5,...,0.614907,0.182116,0.283521,0.716671,0.041032,0.432577,0.302302,0.812673,0.622103,0.290383
74186,202196,1,Cash loans,F,N,Y,1,189000.0,640080.0,31261.5,...,0.855122,0.907023,0.555958,0.114399,0.959646,0.551736,0.793345,0.769783,0.029523,0.605118
65253,272854,0,Cash loans,F,N,N,1,121500.0,104256.0,8194.5,...,0.837285,0.401049,0.896599,0.775044,0.372050,0.355883,0.259412,0.282194,0.438214,0.348245
60400,207628,0,Cash loans,F,N,N,0,112500.0,755190.0,36328.5,...,0.046936,0.164097,0.416916,0.498222,0.366917,0.326498,0.383481,0.743987,0.612620,0.627862
71140,244369,1,Cash loans,F,N,N,1,193500.0,521280.0,25209.0,...,0.245522,0.720827,0.837383,0.520593,0.111493,0.763497,0.666572,0.421767,0.714451,0.916040

In [9]:
# Criando um novo dataframe baseado no original (Original fazia transformações aqui)
df_train_01 = train.copy()
df_test_01 = test.copy()

In [10]:
df_train_01.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
45499,102669,0,Cash loans,F,N,Y,0,157500.0,709033.5,39721.5,...,0.614907,0.182116,0.283521,0.716671,0.041032,0.432577,0.302302,0.812673,0.622103,0.290383
74186,202196,1,Cash loans,F,N,Y,1,189000.0,640080.0,31261.5,...,0.855122,0.907023,0.555958,0.114399,0.959646,0.551736,0.793345,0.769783,0.029523,0.605118
65253,272854,0,Cash loans,F,N,N,1,121500.0,104256.0,8194.5,...,0.837285,0.401049,0.896599,0.775044,0.372050,0.355883,0.259412,0.282194,0.438214,0.348245
60400,207628,0,Cash loans,F,N,N,0,112500.0,755190.0,36328.5,...,0.046936,0.164097,0.416916,0.498222,0.366917,0.326498,0.383481,0.743987,0.612620,0.627862
71140,244369,1,Cash loans,F,N,N,1,193500.0,521280.0,25209.0,...,0.245522,0.720827,0.837383,0.520593,0.111493,0.763497,0.666572,0.421767,0.714451,0.916040

In [11]:
metadados = pod.pod_academy_generate_metadata(df_train_01, ids=['SK_ID_CURR'], targets=['TARGET'], orderby='PC_NULOS')

metadados

,FEATURE,USO_FEATURE,QT_NULOS,PC_NULOS,CARDINALIDADE,TIPO_FEATURE
0,COMMONAREA_MODE,Explicativa,105323,69.90,2681,float64
1,COMMONAREA_AVG,Explicativa,105323,69.90,2721,float64
2,COMMONAREA_MEDI,Explicativa,105323,69.90,2741,float64
3,NONLIVINGAPARTMENTS_AVG,Explicativa,104662,69.46,321,float64
4,NONLIVINGAPARTMENTS_MEDI,Explicativa,104662,69.46,178,float64
...,...,...,...,...,...,...
167,REG_CITY_NOT_WORK_CITY,Explicativa,0,0.00,2,int64
168,REG_CITY_NOT_LIVE_CITY,Explicativa,0,0.00,2,int64
169,LIVE_REGION_NOT_WORK_REGION,Explicativa,0,0.00,2,int64
170,REG_REGION_NOT_WORK_REGION,Explicativa,0,0.00,2,int64
171,var_50,Explicativa,0,0.00,150679,float64

Excluindo variáveis com mais que 70 % de nulos

In [12]:
missing_cutoff = 70

drop_vars_nulos = metadados[(metadados['PC_NULOS'] >= missing_cutoff)]
lista_drop_vars = list(drop_vars_nulos.FEATURE.values)

print('Variáveis que serão excluídas por alto percentual de nulos: ',lista_drop_vars)
# retirando lista de variáveis com alto percentual de nulos
df_train_02 = df_train_01.drop(axis=1,columns=lista_drop_vars)
df_train_02.shape

Variáveis que serão excluídas por alto percentual de nulos:  []

(150679, 172)

Serealização, implantando variáveis selecionadas para serem excluídas/
Artefato.

Nesse caso estamos serealizando uma regressão logista o arquivo pkl (arquivo binário), terá os betas, uma lista com os coeficientes.

In [13]:
# Salvar a lista em um arquivo .pkl
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_drop_nullvar.pkl', 'wb') as f:
    pickle.dump(lista_drop_vars, f)

Realizando o mesmo tratamento na copia de teste

In [14]:
# retirando lista de variáveis com alto percentual de nulos
df_test_02 = df_test_01.drop(axis=1,columns=lista_drop_vars)
df_test_02.shape

(64578, 172)

In [15]:
df_test_02.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
196348,243431,0,Revolving loans,M,N,Y,0,90000.0,180000.0,9000.0,...,0.593565,0.789703,0.254486,0.969768,0.918087,0.939984,0.941608,0.053827,0.571771,0.186664
147976,127962,0,Cash loans,F,N,N,0,225000.0,781920.0,42547.5,...,0.346320,0.912834,0.910227,0.784684,0.485868,0.812601,0.425869,0.335348,0.878763,0.792996
52662,244667,1,Cash loans,M,N,Y,1,112500.0,450000.0,21888.0,...,0.973969,0.671805,0.428278,0.189641,0.765047,0.931675,0.944781,0.270274,0.296258,0.518378
101577,220032,0,Cash loans,F,N,Y,0,225000.0,760225.5,32337.0,...,0.766011,0.533777,0.995612,0.998489,0.318540,0.923508,0.271327,0.558144,0.926976,0.794804
173078,123746,0,Cash loans,F,N,N,0,225000.0,808650.0,26217.0,...,0.608260,0.155219,0.634449,0.650114,0.198636,0.202310,0.193130,0.437779,0.901853,0.126509

In [16]:
# Retirar ID e Target do tratamento de nulos na base de treino
df_train_02 = df_train_02.drop(axis=1, columns=['SK_ID_CURR', 'TARGET'])
df_train_02.head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
45499,Cash loans,F,N,Y,0,157500.0,709033.5,39721.5,657000.0,Unaccompanied,...,0.614907,0.182116,0.283521,0.716671,0.041032,0.432577,0.302302,0.812673,0.622103,0.290383
74186,Cash loans,F,N,Y,1,189000.0,640080.0,31261.5,450000.0,Unaccompanied,...,0.855122,0.907023,0.555958,0.114399,0.959646,0.551736,0.793345,0.769783,0.029523,0.605118
65253,Cash loans,F,N,N,1,121500.0,104256.0,8194.5,90000.0,Unaccompanied,...,0.837285,0.401049,0.896599,0.775044,0.372050,0.355883,0.259412,0.282194,0.438214,0.348245
60400,Cash loans,F,N,N,0,112500.0,755190.0,36328.5,675000.0,Unaccompanied,...,0.046936,0.164097,0.416916,0.498222,0.366917,0.326498,0.383481,0.743987,0.612620,0.627862
71140,Cash loans,F,N,N,1,193500.0,521280.0,25209.0,450000.0,Unaccompanied,...,0.245522,0.720827,0.837383,0.520593,0.111493,0.763497,0.666572,0.421767,0.714451,0.916040

In [17]:
# Retirar ID e Target do tratamento de nulos na base de test
df_test_02 = df_test_02.drop(axis=1, columns=['SK_ID_CURR', 'TARGET'])
df_test_02.head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
196348,Revolving loans,M,N,Y,0,90000.0,180000.0,9000.0,180000.0,Unaccompanied,...,0.593565,0.789703,0.254486,0.969768,0.918087,0.939984,0.941608,0.053827,0.571771,0.186664
147976,Cash loans,F,N,N,0,225000.0,781920.0,42547.5,675000.0,Unaccompanied,...,0.346320,0.912834,0.910227,0.784684,0.485868,0.812601,0.425869,0.335348,0.878763,0.792996
52662,Cash loans,M,N,Y,1,112500.0,450000.0,21888.0,450000.0,Unaccompanied,...,0.973969,0.671805,0.428278,0.189641,0.765047,0.931675,0.944781,0.270274,0.296258,0.518378
101577,Cash loans,F,N,Y,0,225000.0,760225.5,32337.0,679500.0,Unaccompanied,...,0.766011,0.533777,0.995612,0.998489,0.318540,0.923508,0.271327,0.558144,0.926976,0.794804
173078,Cash loans,F,N,N,0,225000.0,808650.0,26217.0,675000.0,Family,...,0.608260,0.155219,0.634449,0.650114,0.198636,0.202310,0.193130,0.437779,0.901853,0.126509

Substituindo os nulos pela média para variáveis numéricas
por "SEM_INFO" para categóricas

In [18]:
# Substituindo os nulos na base de treino
df_train_03, means = pod.pod_custom_fillna(df_train_02)

with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_fillna.pkl', 'wb') as f:
  pickle.dump(means, f)

# Com a função usada POD o pkl de um fillna guarda num objeto serealizado, a variável e o valor da média.

In [19]:
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_fillna.pkl', 'rb') as f:
  loaded_means = pickle.load(f)
loaded_means

{'CNT_CHILDREN': 0.4162092926021542,
 'AMT_INCOME_TOTAL': 168699.04549346626,
 'AMT_CREDIT': 599845.5172917261,
 'AMT_ANNUITY': 27149.62152063395,
 'AMT_GOODS_PRICE': 539122.5637288766,
 'REGION_POPULATION_RELATIVE': 0.020843482310076378,
 'DAYS_BIRTH': -16035.914852102815,
 'DAYS_EMPLOYED': 63599.31629036754,
 'DAYS_REGISTRATION': -4976.067520465273,
 'DAYS_ID_PUBLISH': -2991.8822818756307,
 'OWN_CAR_AGE': 12.035873743060138,
 'FLAG_MOBIL': 0.9999933633751219,
 'FLAG_EMP_PHONE': 0.8204792970486929,
 'FLAG_WORK_PHONE': 0.19891292084497508,
 'FLAG_CONT_MOBILE': 0.9981550182839015,
 'FLAG_PHONE': 0.2809283310879419,
 'FLAG_EMAIL': 0.05709488382588151,
 'CNT_FAM_MEMBERS': 2.153631229302026,
 'REGION_RATING_CLIENT': 2.0532987343956357,
 'REGION_RATING_CLIENT_W_CITY': 2.0322141771580644,
 'HOUR_APPR_PROCESS_START': 12.05614584646832,
 'REG_REGION_NOT_LIVE_REGION': 0.01548988246537341,
 'REG_REGION_NOT_WORK_REGION': 0.05142720618002509,
 'LIVE_REGION_NOT_WORK_REGION': 0.04101434174636147,
 'REG_CITY_NOT_LIVE_CITY': 0.07842499618394069,
 'REG_CITY_NOT_WORK_CITY': 0.23066917088645397,
 'LIVE_CITY_NOT_WORK_CITY': 0.17929505770545331,
 'EXT_SOURCE_1': 0.5031859956528094,
 'EXT_SOURCE_2': 0.5145058417827371,
 'EXT_SOURCE_3': 0.510793838732432,
 'APARTMENTS_AVG': 0.11745182720215999,
 'BASEMENTAREA_AVG': 0.08862181314013688,
 'YEARS_BEGINEXPLUATATION_AVG': 0.9775837776509942,
 'YEARS_BUILD_AVG': 0.7525410325655283,
 'COMMONAREA_AVG': 0.04448259987653232,
 'ELEVATORS_AVG': 0.07933155350847264,
 'ENTRANCES_AVG': 0.14969888118626376,
 'FLOORSMAX_AVG': 0.2261280975558142,
 'FLOORSMIN_AVG': 0.23166274311225016,
 'LANDAREA_AVG': 0.06645004251839737,
 'LIVINGAPARTMENTS_AVG': 0.10087016833179416,
 'LIVINGAREA_AVG': 0.10748022711199477,
 'NONLIVINGAPARTMENTS_AVG': 0.00886710563487407,
 'NONLIVINGAREA_AVG': 0.028449006789784126,
 'APARTMENTS_MODE': 0.1141147040161998,
 'BASEMENTAREA_MODE': 0.08769584542146852,
 'YEARS_BEGINEXPLUATATION_MODE': 0.9769181439796681,
 'YEARS_BUILD_MODE': 0.7596546088165209,
 'COMMONAREA_MODE': 0.04238833230443602,
 'ELEVATORS_MODE': 0.07477473558512453,
 'ENTRANCES_MODE': 0.1451442386445759,
 'FLOORSMAX_MODE': 0.2221441897682785,
 'FLOORSMIN_MODE': 0.22772945662732777,
 'LANDAREA_MODE': 0.06499453638593622,
 'LIVINGAPARTMENTS_MODE': 0.10556124380824447,
 'LIVINGAREA_MODE': 0.10595249729787433,
 'NONLIVINGAPARTMENTS_MODE': 0.008089853749701198,
 'NONLIVINGAREA_MODE': 0.02704224226306327,
 'APARTMENTS_MEDI': 0.1178201174485319,
 'BASEMENTAREA_MEDI': 0.08813050537755053,
 'YEARS_BEGINEXPLUATATION_MEDI': 0.977563354166126,
 'YEARS_BUILD_MEDI': 0.7557931910246228,
 'COMMONAREA_MEDI': 0.04445731105035717,
 'ELEVATORS_MEDI': 0.07843426589332425,
 'ENTRANCES_MEDI': 0.14919804073766763,
 'FLOORSMAX_MEDI': 0.22576540180933236,
 'FLOORSMIN_MEDI': 0.23134518942603807,
 'LANDAREA_MEDI': 0.06731461488143908,
 'LIVINGAPARTMENTS_MEDI': 0.10198328016119554,
 'LIVINGAREA_MEDI': 0.10867976007792798,
 'NONLIVINGAPARTMENTS_MEDI': 0.008691824760414631,
 'NONLIVINGAREA_MEDI': 0.02824043264445006,
 'TOTALAREA_MODE': 0.10255863220206221,
 'OBS_30_CNT_SOCIAL_CIRCLE': 1.419609148716583,
 'DEF_30_CNT_SOCIAL_CIRCLE': 0.1430236042214602,
 'OBS_60_CNT_SOCIAL_CIRCLE': 1.402563505010487,
 'DEF_60_CNT_SOCIAL_CIRCLE': 0.09983686786296901,
 'DAYS_LAST_PHONE_CHANGE': -970.9500562897043,
 'FLAG_DOCUMENT_2': 1.3273249756104036e-05,
 'FLAG_DOCUMENT_3': 0.7095680220866876,
 'FLAG_DOCUMENT_4': 9.291274829272824e-05,
 'FLAG_DOCUMENT_5': 0.01539033309220263,
 'FLAG_DOCUMENT_6': 0.08749062576735975,
 'FLAG_DOCUMENT_7': 0.00016591562195130045,
 'FLAG_DOCUMENT_8': 0.08198886374345463,
 'FLAG_DOCUMENT_9': 0.003962065052197055,
 'FLAG_DOCUMENT_10': 2.6546499512208072e-05,
 'FLAG_DOCUMENT_11': 0.0038890621785384826,
 'FLAG_DOCUMENT_12': 6.636624878052018e-06,
 'FLAG_DOCUMENT_13': 0.003364768813172373,
 'FLAG_DOCUMENT_14': 0.0028869318219526276,
 'FLAG_DOCUMENT_15': 0.0012012291029274151,
 'FLAG_DOCUMENT_16': 0.009994757066346338,
 'FLAG_DOCUMENT_17': 0.0002853748697562368,
 'FLAG_DOCUMENT_18': 0.008129865475613722,
 'FLAG_DOCUMENT_19': 0.0005773863643905255,
 'FLAG_DOCUMENT_20': 0.0004911102409758493,
 'FLAG_DOCUMENT_21': 0.0003318312439026009,
 'AMT_REQ_CREDIT_BUREAU_HOUR': 0.00659433347391021,
 'AMT_REQ_CREDIT_BUREAU_DAY': 0.0068627075106391135,
 'AMT_REQ_CREDIT_BUREAU_WEEK': 0.034505233293716214,
 'AMT_REQ_CREDIT_BUREAU_MON': 0.2686807499137369,
 'AMT_REQ_CREDIT_BUREAU_QRT': 0.2668941456120845,
 'AMT_REQ_CREDIT_BUREAU_YEAR': 1.8933941647816586,
 'var_1': 0.4983958862969508,
 'var_2': 0.4991931386137605,
 'var_3': 0.5007472281057477,
 'var_4': 0.4984707984786316,
 'var_5': 0.49996723684334,
 'var_6': 0.49953646004318447,
 'var_7': 0.5004465445724378,
 'var_8': 0.5008323198761557,
 'var_9': 0.5009915320118933,
 'var_10': 0.4994933361564683,
 'var_11': 0.5000261889735667,
 'var_12': 0.5014489182798342,
 'var_13': 0.5007937786743278,
 'var_14': 0.500415204423777,
 'var_15': 0.5016453539662896,
 'var_16': 0.5007942806094794,
 'var_17': 0.5014112207590378,
 'var_18': 0.5000320817730702,
 'var_19': 0.4985320019373235,
 'var_20': 0.49895263484084174,
 'var_21': 0.4999709295744016,
 'var_22': 0.5007250357343267,
 'var_23': 0.4995410458609803,
 'var_24': 0.5011765926507896,
 'var_25': 0.49937490187126127,
 'var_26': 0.5008623215340943,
 'var_27': 0.49967240376557226,
 'var_28': 0.5002315476860375,
 'var_29': 0.5001708305569905,
 'var_30': 0.4994827099273167,
 'var_31': 0.499670552607236,
 'var_32': 0.5006801500746183,
 'var_33': 0.5005412724960326,
 'var_34': 0.5001365319382552,
 'var_35': 0.5003308410290255,
 'var_36': 0.49908790909025325,
 'var_37': 0.499078612321892,
 'var_38': 0.4999150215684122,
 'var_39': 0.4999425204118565,
 'var_40': 0.5002707900180902,
 'var_41': 0.5000243431783318,
 'var_42': 0.5001440058926552,
 'var_43': 0.4993769079236298,
 'var_44': 0.50004586129538,
 'var_45': 0.5011368701614992,
 'var_46': 0.5003452226263041,
 'var_47': 0.49996767404787373,
 'var_48': 0.5002342451709182,
 'var_49': 0.4999490200157306,
 'var_50': 0.4995645155364712}

In [20]:
# Substituindo os nulos na base de teste usando as médias da base de treino
df_test_03 = pod.pod_custom_fillna_prod(df_test_02, loaded_means)
df_test_03.shape

(64578, 170)

In [21]:
df_test_03.head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,var_41,var_42,var_43,var_44,var_45,var_46,var_47,var_48,var_49,var_50
196348,Revolving loans,M,N,Y,0,90000.0,180000.0,9000.0,180000.0,Unaccompanied,...,0.593565,0.789703,0.254486,0.969768,0.918087,0.939984,0.941608,0.053827,0.571771,0.186664
147976,Cash loans,F,N,N,0,225000.0,781920.0,42547.5,675000.0,Unaccompanied,...,0.346320,0.912834,0.910227,0.784684,0.485868,0.812601,0.425869,0.335348,0.878763,0.792996
52662,Cash loans,M,N,Y,1,112500.0,450000.0,21888.0,450000.0,Unaccompanied,...,0.973969,0.671805,0.428278,0.189641,0.765047,0.931675,0.944781,0.270274,0.296258,0.518378
101577,Cash loans,F,N,Y,0,225000.0,760225.5,32337.0,679500.0,Unaccompanied,...,0.766011,0.533777,0.995612,0.998489,0.318540,0.923508,0.271327,0.558144,0.926976,0.794804
173078,Cash loans,F,N,N,0,225000.0,808650.0,26217.0,675000.0,Family,...,0.608260,0.155219,0.634449,0.650114,0.198636,0.202310,0.193130,0.437779,0.901853,0.126509

Tratamento de categóricas de alta cardinalidade (LabelEncoder)

Determinamos um cutoff de 20, se tiver mais do que 20 usaremos LabelEnconder, e se tiver menos do que 20 faremos one-hot-enconding.

In [22]:
# Identifica colunas para LabelEncoder que não estejam na lista lista_drop_vars
card_cutoff = 20
df_categ_labelenc = metadados[(metadados['CARDINALIDADE'] > card_cutoff) & (metadados['TIPO_FEATURE'] == 'object')]
lista_vars_abt = list(df_train_03.columns)
lista_lenc = list(df_categ_labelenc.FEATURE.values)

for item in lista_drop_vars:
    if item in lista_lenc:
        lista_lenc.remove(item)

print('Lista de vars para Label Encoding: ',lista_lenc)

Lista de vars para Label Encoding:  ['ORGANIZATION_TYPE']

In [23]:
# transforma via LabelEncoder colunas na base de treino
import pickle
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in lista_lenc:
    encoder = LabelEncoder()
    df_train_03[col] = encoder.fit_transform(df_train_03[col])

    # Armazena o encoder para a coluna atual em um dicionário
    encoders[col] = encoder

# Salva o dicionário de encoders e a lista de colunas em um arquivo .pkl
data_to_serialize = {
    'encoders': encoders,
    'columns': lista_lenc
}

with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_labelenc.pkl', 'wb') as f:
    pickle.dump(data_to_serialize, f)

In [24]:
# transforma via LabelEncoder colunas na base de treino
import pickle
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in lista_lenc:
    encoder = LabelEncoder()
    df_train_03[col] = encoder.fit_transform(df_train_03[col])

    # Armazena o encoder para a coluna atual em um dicionário
    encoders[col] = encoder

# Salva o dicionário de encoders e a lista de colunas em um arquivo .pkl
data_to_serialize = {
    'encoders': encoders,
    'columns': lista_lenc
}

with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_labelenc.pkl', 'wb') as f:
    pickle.dump(data_to_serialize, f)

In [25]:
print(data_to_serialize)

{'encoders': {'ORGANIZATION_TYPE': LabelEncoder()}, 'columns': ['ORGANIZATION_TYPE']}

In [26]:
# Exibir os valores únicos na coluna 'ORGANIZATION_TYPE'
unique_values = df_test_03['ORGANIZATION_TYPE'].unique()
print(unique_values)

['Business Entity Type 3' 'Construction' 'School' 'Self-employed'
 'Agriculture' 'Medicine' 'Trade: type 7' 'Trade: type 3' 'XNA'
 'Business Entity Type 2' 'Police' 'Trade: type 2' 'Industry: type 7'
 'Industry: type 3' 'Housing' 'Other' 'Kindergarten' 'Security Ministries'
 'Government' 'Transport: type 4' 'Trade: type 6' 'Business Entity Type 1'
 'University' 'Industry: type 11' 'Insurance' 'Security'
 'Industry: type 9' 'Emergency' 'Transport: type 2' 'Postal' 'Restaurant'
 'Industry: type 5' 'Services' 'Bank' 'Industry: type 4'
 'Transport: type 3' 'Military' 'Culture' 'Telecom' 'Trade: type 1'
 'Hotel' 'Industry: type 1' 'Cleaning' 'Industry: type 12' 'Advertising'
 'Industry: type 6' 'Industry: type 2' 'Mobile' 'Realtor'
 'Industry: type 13' 'Religion' 'Electricity' 'Legal Services'
 'Trade: type 4' 'Transport: type 1' 'Trade: type 5' 'Industry: type 10'
 'Industry: type 8']

In [27]:
print('ORGANIZATION_TYPE' in df_test_03.columns)

True

In [28]:
unique_values_train = df_train_03['ORGANIZATION_TYPE'].unique()
unique_values_test = df_test_03['ORGANIZATION_TYPE'].unique()

print('Valores únicos na base de treino:')
print(unique_values_train)

print('\nValores únicos na base de teste:')
print(unique_values_test)

Valores únicos na base de treino:
[ 5  4 42 39 57 33  2 53  3 40  9 11 20  7 51 56 30 50 14 16 38 31  1 28
 41 34 55 26 27 49 13 12 23 22 43 19  0 44 35  8 47 36 54 46 24 21 17 29
 10 45 32 15 52  6 37 25 48 18]

Valores únicos na base de teste:
['Business Entity Type 3' 'Construction' 'School' 'Self-employed'
 'Agriculture' 'Medicine' 'Trade: type 7' 'Trade: type 3' 'XNA'
 'Business Entity Type 2' 'Police' 'Trade: type 2' 'Industry: type 7'
 'Industry: type 3' 'Housing' 'Other' 'Kindergarten' 'Security Ministries'
 'Government' 'Transport: type 4' 'Trade: type 6' 'Business Entity Type 1'
 'University' 'Industry: type 11' 'Insurance' 'Security'
 'Industry: type 9' 'Emergency' 'Transport: type 2' 'Postal' 'Restaurant'
 'Industry: type 5' 'Services' 'Bank' 'Industry: type 4'
 'Transport: type 3' 'Military' 'Culture' 'Telecom' 'Trade: type 1'
 'Hotel' 'Industry: type 1' 'Cleaning' 'Industry: type 12' 'Advertising'
 'Industry: type 6' 'Industry: type 2' 'Mobile' 'Realtor'
 'Industry: type 13' 'Religion' 'Electricity' 'Legal Services'
 'Trade: type 4' 'Transport: type 1' 'Trade: type 5' 'Industry: type 10'
 'Industry: type 8']

In [29]:
# Carregar os encoders e a lista de colunas
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_labelenc.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

loaded_encoders = loaded_data['encoders']
loaded_columns = loaded_data['columns']

# Suponha df_test_03 como sua base de teste
for col in loaded_columns:
    if col in loaded_encoders:
        try:
            # Transforma a coluna usando o encoder carregado
            df_test_03[col] = loaded_encoders[col].transform(df_test_03[col])
        except ValueError as e:
            # Captura e imprime o erro
            print(f"Erro ao transformar a coluna {col}: {e}")
            # Solução: Criar um mapeamento entre as categorias únicas da base de treino e os rótulos atribuídos pelo LabelEncoder
            # Mapeia os valores únicos para os rótulos atribuídos pelo LabelEncoder na base de treino
            label_mapping = {val: label for val, label in zip(loaded_encoders[col].classes_, loaded_encoders[col].transform(loaded_encoders[col].classes_))}
            # Aplica o mapeamento à coluna correspondente na base de teste usando o método map
            df_test_03[col] = df_test_03[col].map(label_mapping)

Erro ao transformar a coluna ORGANIZATION_TYPE: invalid literal for int() with base 10: 'Business Entity Type 3'

In [30]:
# -- Correção do Erro --
# O erro ocorreu devido à inconsistência nos rótulos atribuídos pela transformação LabelEncoder
# entre as bases de treino e teste. Para resolver isso:

# 1. Durante o treinamento, usamos LabelEncoder para transformar uma coluna categórica na base de treino.
# 2. Salvamos os rótulos atribuídos em um arquivo pickle.

# -- Carregamento do LabelEncoder --
# Ao carregar o modelo em uma nova sessão ou base de teste, utilizamos o LabelEncoder salvo.

# -- Aplicação Correta da Transformação --
# Garantimos consistência aplicando corretamente o LabelEncoder carregado à coluna categórica na base de teste.

Tratamento para categóricas de baixa cardinalidade

In [31]:
print(df_train_03.shape)
print(df_test_03.shape)

(150679, 170)
(64578, 170)

In [32]:
import pickle
from sklearn.preprocessing import OneHotEncoder

card_cutoff = 3
df_categ_onehot = metadados[(metadados['CARDINALIDADE'] <= card_cutoff) & (metadados['TIPO_FEATURE'] == 'object')]
lista_onehot = list(df_categ_onehot.FEATURE.values)
print('Lista de vars para OneHot Encoding: ',lista_onehot)

# Instanciando o encoder
encoder = OneHotEncoder(drop='first', sparse_output=False)

# Aplicando o one-hot encoding
encoded_data = encoder.fit_transform(df_train_03[lista_onehot])
encoded_cols = encoder.get_feature_names_out(lista_onehot)
encoded_df = pd.DataFrame(encoded_data, columns=encoded_cols, index=df_train_03.index)

df_train_03 = pd.concat([df_train_03.drop(lista_onehot, axis=1), encoded_df], axis=1)

# Salva o encoder e a lista de colunas em um arquivo .pkl
data_to_serialize = {
    'encoder': encoder,
    'columns': lista_onehot
}

with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_onehotenc.pkl', 'wb') as f:
    pickle.dump(data_to_serialize, f)

df_train_03.shape

Lista de vars para OneHot Encoding:  ['HOUSETYPE_MODE', 'EMERGENCYSTATE_MODE', 'FLAG_OWN_REALTY', 'FLAG_OWN_CAR', 'CODE_GENDER', 'NAME_CONTRACT_TYPE']

(150679, 174)

In [34]:
# Carregar o encoder e a lista de colunas
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_onehotenc.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

loaded_encoder = loaded_data['encoder']
loaded_columns = loaded_data['columns']

# Suponha df_test_03 como sua base de teste
encoded_data_test = loaded_encoder.transform(df_test_03[loaded_columns])
encoded_cols_test = loaded_encoder.get_feature_names_out(loaded_columns)
encoded_df_test = pd.DataFrame(encoded_data_test, columns=encoded_cols_test, index=df_test_03.index)

df_test_03 = pd.concat([df_test_03.drop(loaded_columns, axis=1), encoded_df_test], axis=1)

df_test_03.shape

(64578, 174)

Aplicar normalização a toda tabela de modelagem tratada ate este ponto

In [35]:
import pickle
from sklearn.preprocessing import StandardScaler

# Excluindo IDs e Targets
df_id_target = metadados[(metadados['USO_FEATURE'] == 'ID') | (metadados['USO_FEATURE'] == 'Target')]
lista_id_target = list(df_id_target.FEATURE.values)
print('Lista de IDs e Target: ',lista_id_target)

# Instanciando o scaler
scaler = StandardScaler()

# Selecionando colunas numéricas
numeric_cols = df_train_03.select_dtypes(include=['float64', 'int64','int32']).columns

# Aplicando a normalização
df_train_03[numeric_cols] = scaler.fit_transform(df_train_03[numeric_cols])

# Salva o scaler em um arquivo .pkl
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

print(scaler)
df_train_03.shape

Lista de IDs e Target:  ['SK_ID_CURR', 'TARGET']
StandardScaler()

(150679, 174)

In [36]:
# Carregar o scaler
with open('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/prd_scaler.pkl', 'rb') as f:
    loaded_scaler = pickle.load(f)

# Suponha df_test_03 como sua base de teste

# Selecionando colunas numéricas
numeric_cols = df_test_03.select_dtypes(include=['float64', 'int64','int32']).columns

# Aplicando a normalização
df_test_03[numeric_cols] = loaded_scaler.fit_transform(df_test_03[numeric_cols])

df_test_03.shape

/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1047: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1052: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1072: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

(64578, 174)

In [37]:
df_test_03.head()

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,...,HOUSETYPE_MODE_block of flats,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,EMERGENCYSTATE_MODE_POD_VERIFICAR,EMERGENCYSTATE_MODE_Yes,FLAG_OWN_REALTY_Y,FLAG_OWN_CAR_Y,CODE_GENDER_M,CODE_GENDER_XNA,NAME_CONTRACT_TYPE_Revolving loans
196348,-0.581516,-0.784592,-1.038705,-1.246965,-0.968061,Unaccompanied,Commercial associate,Secondary / secondary special,Single / not married,With parents,...,-0.981526,-0.069901,-0.063087,1.055094,-0.086808,0.663684,-0.716515,1.388779,-0.005565,3.070985
147976,-0.581516,0.569449,0.454599,1.070650,0.369944,Unaccompanied,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,...,1.018821,-0.069901,-0.063087,-0.947783,-0.086808,-1.506741,-0.716515,-0.720057,-0.005565,-0.325628
52662,0.810888,-0.558918,-0.368861,-0.356603,-0.238240,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,...,-0.981526,-0.069901,15.851114,-0.947783,-0.086808,0.663684,-0.716515,1.388779,-0.005565,-0.325628
101577,-0.581516,0.569449,0.400777,0.365262,0.382107,Unaccompanied,Working,Secondary / secondary special,Married,With parents,...,-0.981526,-0.069901,-0.063087,1.055094,-0.086808,0.663684,-0.716515,-0.720057,-0.005565,-0.325628
173078,-0.581516,0.569449,0.520914,-0.057536,0.369944,Family,State servant,Higher education,Married,House / apartment,...,-0.981526,-0.069901,-0.063087,1.055094,-0.086808,-1.506741,-0.716515,-0.720057,-0.005565,-0.325628

Trazer o id e target para a tabela pós dataprep

In [39]:
abt_train = df_train_03.merge(train[['SK_ID_CURR','TARGET']], left_index=True, right_index=True, how='inner')
abt_test = df_test_03.merge(test[['SK_ID_CURR','TARGET']], left_index=True, right_index=True, how='inner')

print(abt_train.shape)
print(abt_test.shape)

(150679, 176)
(64578, 176)

In [40]:
abt_train.head()

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,...,HOUSETYPE_MODE_terraced house,EMERGENCYSTATE_MODE_POD_VERIFICAR,EMERGENCYSTATE_MODE_Yes,FLAG_OWN_REALTY_Y,FLAG_OWN_CAR_Y,CODE_GENDER_M,CODE_GENDER_XNA,NAME_CONTRACT_TYPE_Revolving loans,SK_ID_CURR,TARGET
45499,-0.577795,-0.103326,0.271059,0.864546,0.319009,Unaccompanied,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,...,-0.062751,-0.950247,-0.087466,0.662808,-0.72079,-0.722077,-0.002576,-0.3251,102669,0
74186,0.810437,0.187303,0.099882,0.282767,-0.241190,Unaccompanied,Working,Higher education,Married,House / apartment,...,-0.062751,1.052358,-0.087466,0.662808,-0.72079,-0.722077,-0.002576,-0.3251,202196,1
65253,0.810437,-0.435473,-1.230301,-1.303511,-1.215451,Unaccompanied,Working,Higher education,Single / not married,Rented apartment,...,-0.062751,-0.950247,-0.087466,-1.508732,-0.72079,-0.722077,-0.002576,-0.3251,272854,0
60400,-0.577795,-0.518510,0.385643,0.631216,0.367722,Unaccompanied,Working,Higher education,Married,House / apartment,...,-0.062751,-0.950247,-0.087466,-1.508732,-0.72079,-0.722077,-0.002576,-0.3251,207628,0
71140,0.810437,0.228821,-0.195039,-0.133453,-0.241190,Unaccompanied,Commercial associate,Secondary / secondary special,Separated,House / apartment,...,-0.062751,-0.950247,-0.087466,-1.508732,-0.72079,-0.722077,-0.002576,-0.3251,244369,1

Salvando tabelas de treino e teste pós preparação dos dados

In [41]:
abt_train.to_csv('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/abt_train.csv')
abt_test.to_csv('/content/drive/MyDrive/Pod_Academy/Data_Science_Pod/Hackathon_Data_Science/DataPrep/abt_test.csv')